# Generated by Django 4.0 on 2024-09-08 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0002_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
        migrations.AddField(
            model_name='cita',
            name='descripcion',
            field=models.CharField(default='Descripción por defecto', max_length=255),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(),
        ),
    ]
