# Generated by Django 4.0 on 2024-09-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0003_remove_cita_estado_cita_descripcion_cita_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
