# Generated by Django 4.0 on 2024-09-09 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0004_paciente_cedula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tratamiento',
            old_name='fecha',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='tratamiento',
            old_name='tipo',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
