# Generated by Django 4.0 on 2024-09-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0005_rename_fecha_tratamiento_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='descripcion',
            field=models.CharField(default='Descripcion por defecto', max_length=255),
        ),
    ]
